<?php

namespace VTC\AnnonceBundle\Entity;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFiveFirst()
	{
		$qb = $this->createQueryBuilder('a')
		->addOrderBy('a.date', 'DESC');

        $qb->setMaxResults(10);

    return $qb->getQuery()->getResult();
	}

	public function getSearchForm($data)
	{
  $qb = $this->createQueryBuilder('a')

  ->where('a.annee >= :annee')
  ->setParameter('annee', $data['annee']);

  if($data['dept'] != '')
  {
    $qb->andwhere('a.dept = :dept')
    ->setParameter('dept', $data['dept']);
  }

  if($data['categorie'] != '')
  {
    $qb->andwhere('a.categorie = :categorie')
    ->setParameter('categorie', $data['categorie']);
  }
  
  if($data['energie'] != '')
  {
    $qb->andwhere('a.energie = :energie')
    ->setParameter('energie', $data['energie']);
  }


  if($data['boitevitesse'] != '')
  {
    $qb->andwhere('a.boitevitesse = :boitevitesse')
    ->setParameter('boitevitesse', $data['boitevitesse']);
  }

  if($data['kmsmin'] != '')
  {
    $qb->andwhere('a.kilometres > :kmsmin')
    ->setParameter('kmsmin', $data['kmsmin']);
  }

  if($data['kmsmax'] != '')
  {
    $qb->andwhere('a.kilometres > :kmsmax')
    ->setParameter('kmsmax', $data['kmsmax']);
  }
   /* 

  if($data['locjour'] != false)
  {
    $qb->andwhere('a.locjour = :locjour')
    ->setParameter('locjour', $data['locjour']);
  }

  if($data['lochebdo'] != true)
  {
    $qb->andwhere('a.lochebdo = :lochebdo')
    ->setParameter('lochebdo', $data['lochebdo']);
  }

  if($data['locmensuel'] != true)
  {
    $qb->andwhere('a.locmensuel = :locmensuel')
    ->setParameter('locmensuel', $data['locmensuel']);
  }

  if($data['doublagebool'] != true)
  {
    $qb->andwhere('a.doublagebool = :doublagebool')
    ->setParameter('doublagebool', $data['doublagebool']);
  }


  
  

 // ->andwhere('a.boitevitesse = :boitevitesse')

->andwhere('a.locjour = :locjour')

  ->andwhere('a.lochebdo = :lochebdo')

  ->andwhere('a.locmensuel = :locmensuel')
    
  ->andwhere('a.doublagebool = :doublagebool')
  */
/*
  ->setParameters(array(


      'kmsmin' => $data['kmsmin'],

      'kmsmax' => $data['kmsmax'],

      'categorie' => $data['categorie'],

      'dept' => $data['dept'],

   //   'energie' => $data['energie'],

      'boitevitesse' => $data['boitevitesse']));
  

      'typelocation' => $data['locmensuel'],

      'typelocation' => $data['locjour'],

      'typelocation' => $data['lochebdo'],

      'typelocation' => $data['doublagebool']


      ));

  if ('typelocation' ==  $data['locjour'] )
        {
      
            $query->andwhere('a.locjour = :locjour')

            ->setParameter( 'locjour', $data['locjour']);

         }


      if ('typelocation' == $data['lochebdo'] )
      {
      
            $query->andwhere('a.lochebdo = :lochebdo')

            ->setParameter( 'lochebdo', $data['lochebdo']);

      }

      if ('typelocation' == $data['locmensuel'])
      {
      
            $query->andwhere('a.locmensuel = :locmensuel')

            ->setParameter( 'locmensuel', $data['locmensuel'] );

      }

      if ('typelocation' == $data['doublagebool'])
      {
      
            $query->andwhere('a.doublagebool = :doublagebool')

            ->setParameter( 'doublagebool', $data['doublagebool'] );

      }
    */

        
  return $qb->getQuery()->getResult();
	}

  public function getAdverts($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;

    $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
  }



}
