<?php

namespace VTC\AnnonceBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPictures()
	{
		$qb = $this->createQueryBuilder('i')
		->leftjoin('i.advert', 'a')
		->addSelect('a')
		->where('i.advert = a.id')
		;

		return $qb
		->getQuery()
    	->getResult()
 		 ;
	}
}
