<?php

namespace VTC\AnnonceBundle\Entity;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
	
}
